### ISSUE TITLE
add HRI hand to open-neuroscience.com

### ISSUE THREAD

**Issue by amchagas** [MrLacquer/HRI-hand-firmware#1]
Hello!

We are reaching out because we would love to have your project listed on [Open Neuroscience](<https://open-neuroscience.com>), and also share information about this project:

Open Neuroscience is a community run project, where we are curating and highlighting open source projects related to neurosciences!

Briefly, we have a website where short descritptions about projects are listed, with links to the projects themselves, their authors, together with images and other links. 

Once a new entry is made, we make a quick check for spam, and publish it. 

Once published, we make people aware of the new entry by [Twitter](https://twitter.com/openneurosci) and a [Facebook](https://www.facebook.com/OpenNeuroscience) group. 

**To add information about their project, developers only need to fill out this [form](https://forms.gle/ByM8thAhZJkHBMQN8)**

In the form, people can add subfields and tags to their entries, so that projects are filterable and searchable on the website!

The reason why we have the form system is that it makes it open for everyone to contribute to the website and allows developers themselves to describe their projects! 

Also, there are so many amazing projects coming out in Neurosciences that it would be impossible for us to keep track and log them all!

Please [get in touch](mailto:openeuroscience@gmail.com) if you have any questions or would like to collaborate!

**Comment by hj26-park** [comment]
Hi, 

How could you know my HRI hand project?
And this is not a Neuroscience topic, is it okay?

**Comment by amchagas** [comment]
Hi,

I saw the publication on HardwareX.

We are already covering other robotic hands in open-neuroscience, as there is a subfield in neurosciences where there is an overlap, with brain-machine interfaces. So if you want to cover it there, we are happy to have it!

**Comment by hj26-park** [comment]
Oh, I see.

Thank you for your attention, and I will submit the posting form.
